version: "3.6"

services:
  app:
    container_name: my-vue-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:$HOME
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"  # Enable polling for file watching
